info_kendaraan = ["B 1978 ZKL", "Supra", 150, "black"]

info_kendaraan.append("Rp. 5.000.000")
info_kendaraan.append(2)
info_kendaraan.insert(2, "Honda")
info_kendaraan.insert(3, "Kendaraan Bermotor")

KodeKendaraan = (info_kendaraan[0])
print("Kode Kendaraan  :", KodeKendaraan)
NamaKendaraan = (info_kendaraan[1])
print("Nama Kendaraan  :", NamaKendaraan)
MerkKendaraan = (info_kendaraan[2])
print("Merek Kendaraan :", MerkKendaraan)
JenisKendaraan = (info_kendaraan[3])
print("Jenis Kendaraan :", JenisKendaraan)
CCKendaraan = (info_kendaraan[4])
print("CC Kendaraan    :", CCKendaraan)
WarnaKendaraan = (info_kendaraan[5])
print("Warna Kendaraan :", WarnaKendaraan)
HargaKendaraan = (info_kendaraan[6])
print("Harga Kendaraan :", HargaKendaraan)
JumlahBan = (info_kendaraan[7])
print("Jumlah Ban      :", JumlahBan)
